const taxa = [
    // id, name, parents, rank, description
    { id: "LUCA", parents: [], description: "e" },
    { id: "세균(Bacteria)", parents: ["LUCA"] },
    { id: "고세균(Archaea)", parents: ["LUCA"] },
    { id: "Promethearchaeati", parents: ["고세균(Archaea)"] },
    { id: "Promethearchaeota", parents: ["Promethearchaeati"] },
    { id: "Pseudomonadati", parents: ["세균(Bacteria)"] },
    { id: "Pseudomonadota", parents: ["Pseudomonadati"] },
    { id: "Alphaproteobacteria", parents: ["Pseudomonadota"] },
    { id: "진핵생물(Eukaryota)", parents: ["Alphaproteobacteria", "Promethearchaeota"] },
    { id: "Opimoda", parents: ["진핵생물(Eukaryota)"] },
    { id: "Podiata", parents: ["Opimoda"] },
    { id: "Amorphea", parents: ["Podiata"] },
    { id: "Obazoa", parents: ["Amorphea"] },
    { id: "후편모생물(Opisthokonta)", parents: ["Obazoa"] },
    { id: "Holozoa", parents: ["후편모생물(Opisthokonta)"] },
    { id: "Filozoa", parents: ["Holozoa"] },
    { id: "Choanozoa", parents: ["Filozoa"] },
    { id: "동물계(Animalia)", parents: ["Choanozoa"] },
    { id: "Myriazoa", parents: ["동물계(Animalia)"] },
    { id: "ParaHoxozoa", parents: ["Myriazoa"] },
    { id: "좌우대칭동물(Bilateria)", parents: ["ParaHoxozoa"] },
    { id: "신장동물(Nephrozoa)", parents: ["좌우대칭동물(Bilateria)"] },
    { id: "후구동물(Deuterostomia)", parents: ["신장동물(Nephrozoa)"] },
    { id: "선구동물(Protostomia)", parents: ["신장동물(Nephrozoa)"] },
    { id: "탈피동물(Ecdysozoa)", parents: ["선구동물(Protostomia)"] },
    { id: "범절지동물(Panarthropoda)", parents: ["탈피동물(Ecdysozoa)"] },
    { id: "Tactopoda", parents: ["범절지동물(Panarthropoda)"] },
    { id: "절지동물문(Arthropoda)", parents: ["Tactopoda"] },
    { id: "Deuteropoda", parents: ["절지동물문(Arthropoda)"] },
    { id: "Antennulata", parents: ["Deuteropoda"] },
    { id: "Mandibulata", parents: ["Antennulata"] },
    { id: "범각갑류(Pancrustacea)", parents: ["Mandibulata"] },
    { id: "Altocrustacea", parents: ["범각갑류(Pancrustacea)"] },
    { id: "Allotriocarida", parents: ["Altocrustacea"] },
    { id: "Labiocarida", parents: ["Allotriocarida"] },
    { id: "육각아문(Hexapoda)", parents: ["Labiocarida"] },
    { id: "곤충강(Insecta)", parents: ["육각아문(Hexapoda)"] },
    { id: "Dicondylia", parents: ["곤충강(Insecta)"] },
    { id: "유시아강(Pterygota)", parents: ["Dicondylia"] },
    { id: "신시하강(Neoptera)", parents: ["유시아강(Pterygota)"] },
    { id: "Eumetabola", parents: ["신시하강(Neoptera)"] },
    { id: "Holometabola", parents: ["Eumetabola"] },
    { id: "Aparaglossata", parents: ["Holometabola"] },
    { id: "Panorpida", parents: ["Aparaglossata"] },
    { id: "Amphiesmenoptera", parents: ["Panorpida"] },
    { id: "나비목(Lepidoptera)", parents: ["Amphiesmenoptera"] },
    { id: "흡관아목(Glossata)", parents: ["나비목(Lepidoptera)"] },
    { id: "Coelolepida", parents: ["흡관아목(Glossata)"] },
    { id: "이맥하목(Heteroneura)", parents: ["Coelolepida"] },
    { id: "Eulepidoptera", parents: ["이맥하목(Heteroneura)"] },
    { id: "이문군(Ditrysia)", parents: ["Eulepidoptera"] },
    { id: "Apoditrysia", parents: ["이문군(Ditrysia)"] },
    { id: "Obtectomera", parents: ["Apoditrysia"] },
    { id: "명나방상과(Pyraloidea)", parents: ["Obtectomera"] },
    { id: "풀명나방과(Crambidae)", parents: ["명나방상과(Pyraloidea)"] },
    { id: "Spilomelinae", parents: ["풀명나방과(Crambidae)"] },
    { id: "Margaroniini", parents: ["Spilomelinae"] },
    { id: "Cydalima", parents: ["Margaroniini"] },
    { id: "회양목명나방(Cydalima perspectails)", parents: ["Cydalima"] },
    { id: "호랑나비상과(Papilionoidea)", parents: ["Obtectomera"] },
    { id: "흰나비과(Pieridae)", parents: ["호랑나비상과(Papilionoidea)"] },
    { id: "흰나비아과(Pierinae)", parents: ["흰나비과(Pieridae)"] },
    { id: "흰나비족(Pierini)", parents: ["흰나비아과(Pierinae)"] },
    { id: "흰나비속(Pieris)", parents: ["흰나비족(Pierini)"] },
    { id: "배추흰나비(Pieris rapae)", parents: ["흰나비속(Pieris)"] },
    { id: "뿔나방상과(Gelechioidea)", parents: ["Obtectomera"] },
    { id: "뿔나방과(Gelechiidae)", parents: ["뿔나방상과(Gelechioidea)"] },
    { id: "삼각수염뿔나방아과(Dichomeridinae)", parents: ["뿔나방과(Gelechiidae)"] },
    { id: "삼각수염뿔나방속(Dichomeris)", parents: ["삼각수염뿔나방아과(Dichomeridinae)"] },
    { id: "갈색뿔나방(Dichomeris heriguronis)", parents: ["삼각수염뿔나방속(Dichomeris)"] },
    { id: "벌상목(Hymenopterida)", parents: ["Holometabola"] },
    { id: "벌목(Hymenoptera)", parents: ["벌상목(Hymenopterida)"] },
    { id: "Unicalcarida", parents: ["벌목(Hymenoptera)"] },
    { id: "parasitism", parents: ["Unicalcarida"] },
    { id: "벌아목(Apocrita)", parents: ["parasitism"] },
    { id: "Aculeata", parents: ["벌아목(Apocrita)"] },
    { id: "Euaculeata", parents: ["Aculeata"] },
    { id: "개미상과(Formicoidea)", parents: ["Euaculeata"] },
    { id: "개미과(Formicidae)", parents: ["개미상과(Formicoidea)"] },
    { id: "Formicoid", parents: ["개미과(Formicidae)"] },
    { id: "두마디개미아과(Myrmicinae)", parents: ["Formicoid"] },
    { id: "Crematogastrini", parents: ["두마디개미아과(Myrmicinae)"] },
    { id: "그물등개미속(Pristomyrmex)", parents: ["Crematogastrini"] },
    { id: "그물등개미(Pristomyrmex punctatus)", parents: ["그물등개미속(Pristomyrmex)"] },
    { id: "꿀벌상과(Apoidea)", parents: ["Euaculeata"] },
    { id: "꿀벌류(Anthophila)", parents: ["꿀벌상과(Apoidea)"] },
    { id: "long-tongued bees", parents: ["꿀벌류(Anthophila)"] },
    { id: "꿀벌과(Apidae)", parents: ["long-tongued bees"] },
    { id: "꿀벌아과(Apinae)", parents: ["꿀벌과(Apidae)"] },
    { id: "꿀벌족(Apini)", parents: ["꿀벌아과(Apinae)"] },
    { id: "꿀벌속(Apis)", parents: ["꿀벌족(Apini)"] },
    { id: "서양꿀벌(Apis melifera)", parents: ["꿀벌속(Apis)"] },
    { id: "Paraneoptera", parents: ["Eumetabola"] },
    { id: "Condylognatha", parents: ["Paraneoptera"] },
    { id: "노린재목(Hemiptera)", parents: ["Condylognatha"] },
    { id: "노린재아목(Heteroptera)", parents: ["노린재목(Hemiptera)"] },
    { id: "노린재하목(Pentatomomorpha)", parents: ["노린재아목(Heteroptera)"] },
    { id: "노린재상과(Pentatomoidea)", parents: ["노린재하목(Pentatomomorpha)"] },
    { id: "노린재과(Pentatomidae)", parents: ["노린재상과(Pentatomoidea)"] },
    { id: "노린재아과(Pentatominae)", parents: ["노린재과(Pentatomidae)"] },
    { id: "썩덩나무노린재족(Cappaeini)", parents: ["노린재아과(Pentatominae)"] },
    { id: "썩덩나무노린재속(Halyomorpha)", parents: ["썩덩나무노린재족(Cappaeini)"] },
    { id: "썩덩나무노린재(Halyomorpha halys)", parents: ["썩덩나무노린재속(Halyomorpha)"] },
    { id: "Polyneoptera", parents: ["신시하강(Neoptera)"] },
    { id: "망시상목(Dictyoptera)", parents: ["Polyneoptera"] },
    { id: "바퀴목(Blattodea)", parents: ["망시상목(Dictyoptera)"] },
    { id: "바퀴상과(Blaberoidea)", parents: ["바퀴목(Blattodea)"] },
    { id: "바퀴과(Ectobiidae)", parents: ["바퀴상과(Blaberoidea)"] },
    { id: "바퀴아과(Blattellinae)", parents: ["바퀴과(Ectobiidae)"] },
    { id: "바퀴속(Blattella)", parents: ["바퀴아과(Blattellinae)"] },
    { id: "산바퀴(Blattella nipponica)", parents: ["바퀴속(Blattella)"] },
    { id: "메뚜기목(Orthoptera)", parents: ["Polyneoptera"] },
    { id: "메뚜기아목(Caelifera)", parents: ["메뚜기목(Orthoptera)"] },
    { id: "메뚜기하목(Acrididea)", parents: ["메뚜기아목(Caelifera)"] },
    { id: "모메뚜기상과(Tetrigoidea)", parents: ["메뚜기하목(Acrididea)"] },
    { id: "모메뚜기과(Tetrigidae)", parents: ["모메뚜기상과(Tetrigoidea)"] },
    { id: "모메뚜기아과(Tetriginae)", parents: ["모메뚜기과(Tetrigidae)"] },
    { id: "모메뚜기족(Tetrigini)", parents: ["모메뚜기아과(Tetriginae)"] },
    { id: "모메뚜기속(Tetrix)", parents: ["모메뚜기족(Tetrigini)"] },
    { id: "모메뚜기(Tetrix japonica)", parents: ["모메뚜기속(Tetrix)"] },
    { id: "Communostraca", parents: ["Altocrustacea"] },
    { id: "Malacostraca", parents: ["Communostraca"] },
    { id: "Stomatocarida", parents: ["Malacostraca"] },
    { id: "Syneucarida", parents: ["Stomatocarida"] },
    { id: "진하상목(Eucarida)", parents: ["Syneucarida"] },
    { id: "십각목(Decapoda)", parents: ["진하상목(Eucarida)"] },
    { id: "범배아목(Pleocyemata)", parents: ["십각목(Decapoda)"] },
    { id: "Reptantia", parents: ["범배아목(Pleocyemata)"] },
    { id: "게하목(Brachyura)", parents: ["Reptantia"] },
    { id: "Eubrachyura", parents: ["게하목(Brachyura)"] },
    { id: "Thoracotremata", parents: ["Eubrachyura"] },
    { id: "사각게과(Sesarmidae)", parents: ["Thoracotremata"] },
    { id: "도둑게속(Chiromantes)", parents: ["사각게과(Sesarmidae)"] },
    { id: "도둑게(Chiromantes haematocheir)", parents: ["도둑게속(Chiromantes)"] },
    { id: "Panchelicerata", parents: ["Deuteropoda"] },
    { id: "협각아문(Chelicerata)", parents: ["Panchelicerata"] },
    { id: "Euchelicerata", parents: ["협각아문(Chelicerata)"] },
    { id: "Prosomapoda", parents: ["Euchelicerata"] },
    { id: "Planaterga", parents: ["Prosomapoda"] },
    { id: "Dekatriata", parents: ["Planaterga"] },
    { id: "Sclerophorata", parents: ["Dekatriata"] },
    { id: "거미강(Arachnida)", parents: ["Sclerophorata"] },
    { id: "Arachnopulmonata", parents: ["거미강(Arachnida)"] },
    { id: "Pantetrapulmonata", parents: ["Arachnopulmonata"] },
    { id: "Tetrapulmonata", parents: ["Pantetrapulmonata"] },
    { id: "Serikodiastida", parents: ["Tetrapulmonata"] },
    { id: "거미목(Araneae)", parents: ["Serikodiastida"] },
    { id: "뒷실젖거미아목(Opisthothelae)", parents: ["거미목(Araneae)"] },
    { id: "새실젖거미하목(Araneomorphae)", parents: ["뒷실젖거미아목(Opisthothelae)"] },
    { id: "Entelegynae", parents: ["새실젖거미하목(Araneomorphae)"] },
    { id: "RTA clade", parents: ["Entelegynae"] },
    { id: "Dionycha", parents: ["RTA clade"] },
    { id: "깡충거미과(Salticidae)", parents: ["Dionycha"] },
    { id: "깡충거미아과(Salticinae)", parents: ["깡충거미과(Salticidae)"] },
    { id: "Salticoida", parents: ["깡충거미아과(Salticinae)"] },
    { id: "띠깡충거미속(Siler)", parents: ["Salticoida"] },
    { id: "청띠깡충거미(Siler cupreus)", parents: ["띠깡충거미속(Siler)"] },
    { id: "Ambulacraria", parents: ["후구동물(Deuterostomia)"] },
    { id: "극피동물문(Echinodermata)", parents: ["Ambulacraria"] },
    { id: "Eleutherozoa", parents: ["극피동물문(Echinodermata)"] },
    { id: "Asterozoa", parents: ["Eleutherozoa"] },
    { id: "불가사리강(Asteroidea)", parents: ["Asterozoa"] },
    { id: "연변상목(Valvatacea)", parents: ["불가사리강(Asteroidea)"] },
    { id: "연변목(Valvatida)", parents: ["연변상목(Valvatacea)"] },
    { id: "별불가사리과(Asterinidae)", parents: ["연변목(Valvatida)"] },
    { id: "별불가사리속(Patiria)", parents: ["별불가사리과(Asterinidae)"] },
    { id: "별불가사리(Patiria pectinifera)", parents: ["별불가사리속(Patiria)"] },
    { id: "척삭동물문(Chordata)", parents: ["후구동물(Deuterostomia)"] },
    { id: "Olfactores", parents: ["척삭동물문(Chordata)"] },
    { id: "척추동물(Vertebrata)", parents: ["Olfactores"] },
    { id: "유악류(Gnathostomata)", parents: ["척추동물(Vertebrata)"] },
    { id: "진유악류(Eugnathostomat)", parents: ["유악류(Gnathostomata)"] },
    { id: "경골어류(Osteichthyes)", parents: ["진유악류(Eugnathostomat)"] },
    { id: "육기어류(Sarcopterygii)", parents: ["경골어류(Osteichthyes)"] },
    { id: "Rhipidistia", parents: ["육기어류(Sarcopterygii)"] },
    { id: "사지형어류(Tetrapodomorpha)", parents: ["Rhipidistia"] },
    { id: "네발동물(Tetrapoda)", parents: ["사지형어류(Tetrapodomorpha)"] },
    { id: "Reptiliomorpha", parents: ["네발동물(Tetrapoda)"] },
    { id: "양막류(Amniota)", parents: ["Reptiliomorpha"] },
    { id: "석형류(Sauropsida)", parents: ["양막류(Amniota)"] },
    { id: "Neoreptilia", parents: ["석형류(Sauropsida)"] },
    { id: "Parapleurota", parents: ["Neoreptilia"] },
    { id: "Neodiapsida", parents: ["Parapleurota"] },
    { id: "Sauria", parents: ["Neodiapsida"] },
    { id: "Archosauromorpha", parents: ["Sauria"] },
    { id: "Archelosauria", parents: ["Archosauromorpha"] },
    { id: "Archosauriformes", parents: ["Archelosauria"] },
    { id: "Eucrocopoda", parents: ["Archosauriformes"] },
    { id: "지배파충류(Archosauria)", parents: ["Eucrocopoda"] },
    { id: "Avemetatarsalia", parents: ["지배파충류(Archosauria)"] },
    { id: "Ornithodira", parents: ["Avemetatarsalia"] },
    { id: "공룡(Dinosauria)", parents: ["Ornithodira"] },
    { id: "용반류(Saurischia)", parents: ["공룡(Dinosauria)"] },
    { id: "Eusaurischia", parents: ["용반류(Saurischia)"] },
    { id: "수각류(Theropoda)", parents: ["Eusaurischia"] },
    { id: "Neotheropoda", parents: ["수각류(Theropoda)"] },
    { id: "Averostra", parents: ["Neotheropoda"] },
    { id: "Tetanurae", parents: ["Averostra"] },
    { id: "Coelurosauria", parents: ["Tetanurae"] },
    { id: "Tyrannoraptora", parents: ["Coelurosauria"] },
    { id: "Maniraptoromorpha", parents: ["Tyrannoraptora"] },
    { id: "Neocoelurosauria", parents: ["Maniraptoromorpha"] },
    { id: "Maniraptoriformes", parents: ["Neocoelurosauria"] },
    { id: "Maniraptora", parents: ["Maniraptoriformes"] },
    { id: "Pennaraptora", parents: ["Maniraptora"] },
    { id: "Paraves", parents: ["Pennaraptora"] },
    { id: "Avialae", parents: ["Paraves"] },
    { id: "Pygostylia", parents: ["Avialae"] },
    { id: "Ornithothoraces", parents: ["Pygostylia"] },
    { id: "Ornithuromorpha", parents: ["Ornithothoraces"] },
    { id: "Ornithurae", parents: ["Ornithuromorpha"] },
    { id: "조강(Aves)", parents: ["Ornithurae"] },
    { id: "신악하강(Neognathae)", parents: ["조강(Aves)"] },
    { id: "신조류(Neoaves)", parents: ["신악하강(Neognathae)"] },
    { id: "Columbaves", parents: ["신조류(Neoaves)"] },
    { id: "Columbimorphae", parents: ["Columbaves"] },
    { id: "비둘기목(Columbiformes)", parents: ["Columbimorphae"] },
    { id: "비둘기과(Columbidae)", parents: ["비둘기목(Columbiformes)"] },
    { id: "비둘기아과(Columbinae)", parents: ["비둘기과(Columbidae)"] },
    { id: "멧비둘기속(Streptopelia)", parents: ["비둘기아과(Columbinae)"] },
    { id: "멧비둘기종(Streptopelia orientalis)", parents: ["멧비둘기속(Streptopelia)"] },
    { id: "멧비둘기(Streptopelia orientalis orientalis)", parents: ["멧비둘기종(Streptopelia orientalis)"] },
    { id: "비둘기속(Columba)", parents: ["비둘기아과(Columbinae)"] },
    { id: "바위비둘기종 (Columba livia)", parents: ["비둘기속(Columba)"] },
    { id: "집비둘기(Columba livia domestica)", parents: ["바위비둘기종 (Columba livia)"] },
    { id: "Elementaves", parents: ["신조류(Neoaves)"] },
    { id: "Phaethoquornithes", parents: ["Elementaves"] },
    { id: "수조류(Aequornithes)", parents: ["Phaethoquornithes"] },
    { id: "Feraequornithes", parents: ["수조류(Aequornithes)"] },
    { id: "Pelecanimorphae", parents: ["Feraequornithes"] },
    { id: "Pelecanes", parents: ["Pelecanimorphae"] },
    { id: "사다새목(Pelecaniformes)", parents: ["Pelecanes"] },
    { id: "백로과(Ardeidae)", parents: ["사다새목(Pelecaniformes)"] },
    { id: "백로아과(Ardeinae)", parents: ["백로과(Ardeidae)"] },
    { id: "백로속(Ardea)", parents: ["백로아과(Ardeinae)"] },
    { id: "대백로종(Ardea alba)", parents: ["백로속(Ardea)"] },
    { id: "중대백로(Ardea alba modesta)", parents: ["대백로종(Ardea alba)"] },
    { id: "왜가리종(Ardea cinerea)", parents: ["백로속(Ardea)"] },
    { id: "왜가리(Ardea cinerea jouyi)", parents: ["왜가리종(Ardea cinerea)"] },
    { id: "육조류(Telluraves)", parents: ["신조류(Neoaves)"] },
    { id: "Australaves", parents: ["육조류(Telluraves)"] },
    { id: "Eufalconimorphae", parents: ["Australaves"] },
    { id: "Psittacopasseres", parents: ["Eufalconimorphae"] },
    { id: "참새목(Passeriformes)", parents: ["Psittacopasseres"] },
    { id: "Eupasseres", parents: ["참새목(Passeriformes)"] },
    { id: "참새아목(Passeri)", parents: ["Eupasseres"] },
    { id: "까마귀하목(Corvides)", parents: ["참새아목(Passeri)"] },
    { id: "까마귀상과(Corvoidea)", parents: ["까마귀하목(Corvides)"] },
    { id: "까마귀과(Corvidae)", parents: ["까마귀상과(Corvoidea)"] },
    { id: "까마귀아과(Corvinae)", parents: ["까마귀과(Corvidae)"] },
    { id: "까치속(Pica)", parents: ["까마귀아과(Corvinae)"] },
    { id: "까치(Pica serica)", parents: ["까치속(Pica)"] },
    { id: "꾀꼬리상과(Orioloidea)", parents: ["까마귀하목(Corvides)"] },
    { id: "꾀꼬리과(Oriolidae)", parents: ["꾀꼬리상과(Orioloidea)"] },
    { id: "꾀꼬리속(Oriolus)", parents: ["꾀꼬리과(Oriolidae)"] },
    { id: "꾀꼬리종(Oriolus chinensis)", parents: ["꾀꼬리속(Oriolus)"] },
    { id: "꾀꼬리(Oriolus chinensis diffusus", parents: ["꾀꼬리종(Oriolus chinensis)"] },
    { id: "Perisoreinae", parents: ["까마귀과(Corvidae)"] },
    { id: "물까치속(Cyanopica)", parents: ["Perisoreinae"] },
    { id: "물까치(Cyanopica cyanus)", parents: ["물까치속(Cyanopica)"] },
    { id: "참새하목(Passerides)", parents: ["참새아목(Passeri)"] },
    { id: "참새소목(Passerida)", parents: ["참새하목(Passerides)"] },
    { id: "참새과(Passeridae)", parents: ["참새소목(Passerida)"] },
    { id: "참새속(Passer)", parents: ["참새과(Passeridae)"] },
    { id: "참새(Passer montanus)", parents: ["참새속(Passer)"] },
    { id: "Sylviida", parents: ["참새하목(Passerides)"] },
    { id: "Sylvioidea", parents: ["Sylviida"] },
    { id: "직박구리과(Pycnonotidae)", parents: ["Sylvioidea"] },
    { id: "mainly Asian clade", parents: ["직박구리과(Pycnonotidae)"] },
    { id: "직박구리속(Hypsipetes)", parents: ["mainly Asian clade"] },
    { id: "직박구리종(Hypsipetes amaurotis)", parents: ["직박구리속(Hypsipetes)"] },
    { id: "직박구리(Hypsipetes amaurotis amaurotis)", parents: ["직박구리종(Hypsipetes amaurotis)"] },
    { id: "단궁류(Synapsida)", parents: ["양막류(Amniota)"] },
    { id: "Eupelycosauria", parents: ["단궁류(Synapsida)"] },
    { id: "Sphenacomorpha", parents: ["Eupelycosauria"] },
    { id: "Sphenacodontia", parents: ["Sphenacomorpha"] },
    { id: "Sphenacodontoidea", parents: ["Sphenacodontia"] },
    { id: "수궁류(Therapsida)", parents: ["Sphenacodontoidea"] },
    { id: "Theriodontia", parents: ["수궁류(Therapsida)"] },
    { id: "Eutheriodontia", parents: ["Theriodontia"] },
    { id: "견치류(Cynodontia)", parents: ["Eutheriodontia"] },
    { id: "상견치류(Epicynodontia)", parents: ["견치류(Cynodontia)"] },
    { id: "진견치류(Eucynodontia)", parents: ["상견치류(Epicynodontia)"] },
    { id: "Probainognathia", parents: ["진견치류(Eucynodontia)"] },
    { id: "Prozostrodontia", parents: ["Probainognathia"] },
    { id: "Mammaliamorpha", parents: ["Prozostrodontia"] },
    { id: "Mammaliaformes", parents: ["Mammaliamorpha"] },
    { id: "포유동물강(Mammalia)", parents: ["Mammaliaformes"] },
    { id: "Theriimorpha", parents: ["포유동물강(Mammalia)"] },
    { id: "Theriiformes", parents: ["Theriimorpha"] },
    { id: "Trechnotheria", parents: ["Theriiformes"] },
    { id: "Cladotheria", parents: ["Trechnotheria"] },
    { id: "Zatheria", parents: ["Cladotheria"] },
    { id: "Tribosphenida", parents: ["Zatheria"] },
    { id: "수아강(Theria)", parents: ["Tribosphenida"] },
    { id: "진수하강(Eutheria)", parents: ["수아강(Theria)"] },
    { id: "유태반류(Placentalia)", parents: ["진수하강(Eutheria)"] },
    { id: "Boreoeutheria", parents: ["유태반류(Placentalia)"] },
    { id: "영장상목(Euarchontoglires)", parents: ["Boreoeutheria"] },
    { id: "설치동물(Glires)", parents: ["영장상목(Euarchontoglires)"] },
    { id: "Simplicidentata", parents: ["설치동물(Glires)"] },
    { id: "설치목(Rodentia)", parents: ["Simplicidentata"] },
    { id: "다람쥐아목(Sciuromorpha)", parents: ["설치목(Rodentia)"] },
    { id: "청설모과(Sciuridae)", parents: ["다람쥐아목(Sciuromorpha)"] },
    { id: "청설모아과(Sciurinae)", parents: ["청설모과(Sciuridae)"] },
    { id: "청설모족(Sciurini)", parents: ["청설모아과(Sciurinae)"] },
    { id: "청설모속(Sciurus)", parents: ["청설모족(Sciurini)"] },
    { id: "청설모종(Sciurus vulgaris)", parents: ["청설모속(Sciurus)"] },
    { id: "청설모(Sciurus vulgaris mantchuricus", parents: ["청설모종(Sciurus vulgaris)"] },
    { id: "Holomycota", parents: ["후편모생물(Opisthokonta)"] },
    { id: "균계(Fungi)", parents: ["Holomycota"] },
    { id: "Amastigomycota", parents: ["균계(Fungi)"] },
    { id: "Symbiomycota", parents: ["Amastigomycota"] },
    { id: "쌍핵균아계(Dikarya)", parents: ["Symbiomycota"] },
    { id: "자낭균문(Ascomycota)", parents: ["쌍핵균아계(Dikarya)"] },
    { id: "Saccharomyceta", parents: ["자낭균문(Ascomycota)"] },
    { id: "주발버섯아문(Pezizomycotina)", parents: ["Saccharomyceta"] },
    { id: "두건버섯류(Leotiomyceta)", parents: ["주발버섯아문(Pezizomycotina)"] },
    { id: "Dothideomyceta", parents: ["두건버섯류(Leotiomyceta)"] },
    { id: "흰가시동충하초강(Eurotiomycetes)", parents: ["Dothideomyceta"] },
    { id: "흰가시동충하초아강(Eurotiomycetidae)", parents: ["흰가시동충하초강(Eurotiomycetes)"] },
    { id: "흰가시동충하초목(Eurotiales)", parents: ["흰가시동충하초아강(Eurotiomycetidae)"] },
    { id: "누룩곰팡이과(Aspergillaceae)", parents: ["흰가시동충하초목(Eurotiales)"] },
    { id: "누룩곰팡이속(Aspergillus)", parents: ["누룩곰팡이과(Aspergillaceae)"] },
    { id: "검은아스페곰팡이(Aspergillus niger)", parents: ["누룩곰팡이속(Aspergillus)"] },
    { id: "쌍편모생물(Diphoda)", parents: ["진핵생물(Eukaryota)"] },
    { id: "Diaphoretickes", parents: ["쌍편모생물(Diphoda)"] },
    { id: "CAM", parents: ["Diaphoretickes"] },
    { id: "Bacillati", parents: ["세균(Bacteria)"] },
    { id: "남세균문(Cyanobacteriota)", parents: ["Bacillati"] },
    { id: "원시색소체생물(Archaeplastida)", parents: ["CAM", "남세균문(Cyanobacteriota)"] },
    { id: "식물계(Plantae)", parents: ["원시색소체생물(Archaeplastida)"] },
    { id: "유배식물(Embryophytes)", parents: ["식물계(Plantae)"] },
    { id: "Polysporangiophytes", parents: ["유배식물(Embryophytes)"] },
    { id: "관다발식물(Tracheophytes)", parents: ["Polysporangiophytes"] },
    { id: "종자식물(Spermatophytes)", parents: ["관다발식물(Tracheophytes)"] },
    { id: "속씨식물(Angiosperms)", parents: ["종자식물(Spermatophytes)"] },
    { id: "Mesangiospermae", parents: ["속씨식물(Angiosperms)"] },
    { id: "진정쌍떡잎식물(Eudicots)", parents: ["Mesangiospermae"] },
    { id: "Core eudicots", parents: ["진정쌍떡잎식물(Eudicots)"] },
    { id: "Superasterids", parents: ["Core eudicots"] },
    { id: "국화군(Asterids)", parents: ["Superasterids"] },
    { id: "Campanulids", parents: ["국화군(Asterids)"] },
    { id: "국화목(Asterales)", parents: ["Campanulids"] },
    { id: "국화과(Asteraceae)", parents: ["국화목(Asterales)"] },
    { id: "국화아과(Asteroideae)", parents: ["국화과(Asteraceae)"] },
    { id: "기생초족(Coreopsideae)", parents: ["국화아과(Asteroideae)"] },
    { id: "기생초속(Coreopsis)", parents: ["기생초족(Coreopsideae)"] },
    { id: "기생초(Coreopsis tinctoria)", parents: ["기생초속(Coreopsis)"] },
    { id: "겉씨식물(Gymnospermae)", parents: ["종자식물(Spermatophytes)"] },
    { id: "피자식물문(Pinophyta)", parents: ["겉씨식물(Gymnospermae)"] },
    { id: "소나무강(Pinopsida)", parents: ["피자식물문(Pinophyta)"] },
    { id: "소나무아강(Pinidae)", parents: ["소나무강(Pinopsida)"] },
    { id: "소나무목(Pinales)", parents: ["소나무아강(Pinidae)"] },
    { id: "소나무과(Pinaceae)", parents: ["소나무목(Pinales)"] },
    { id: "소나무아과(Pinoideae)", parents: ["소나무과(Pinaceae)"] },
    { id: "소나무속(Pinus)", parents: ["소나무아과(Pinoideae)"] },
    { id: "소나무아속(Pinus subgenus. Pinus)", parents: ["소나무속(Pinus)"] },
    { id: "Pinus section. Trifoliae", parents: ["소나무아속(Pinus subgenus. Pinus)"] },
    { id: "Pinus subsection. Australes", parents: ["Pinus section. Trifoliae"] },
    { id: "리기다소나무(Pinus rigida)", parents: ["Pinus subsection. Australes"] }
];